# Generated by Django 3.2.8 on 2021-12-05 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='всего расписаний')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Отслеживание',
                'verbose_name_plural': 'Отслеживание',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('ordinal_place', models.CharField(default=1, max_length=255, verbose_name='Порядковое место в списке факультетов')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
                ('title', models.CharField(max_length=255, verbose_name='Номер группы')),
                ('url_table', models.CharField(default='ui_interface/tables/.html', max_length=255, verbose_name='url')),
                ('url_all_tables', models.CharField(default='ui_interface/tables/.html', max_length=255, verbose_name='url')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Номер группы для URL поиска')),
                ('fac', models.CharField(choices=[('Первый курс', '1'), ('Второй курс', '2'), ('Третий курс', '3'), ('Четвертый курс', '4'), ('Пятый курс', '5'), ('Шестой курс', '6'), ('Седьмой курс', '7'), ('Восьмой курс', '8')], max_length=20, verbose_name='Курс')),
                ('price', models.CharField(default=10, max_length=255, verbose_name='Условная единица')),
                ('old_price', models.CharField(default=1, max_length=255, verbose_name='Условная единица')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Таблица Расписания',
                'verbose_name_plural': 'Таблица Расписаний',
            },
        ),
        migrations.CreateModel(
            name='SlideProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Отслеживаемое')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Расписание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расписание в отлеживаемом',
                'verbose_name_plural': 'Расписание в отслеживаемом',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
    ]
